apiVersion: v1
kind: DeploymentConfig
metadata:
  name: wstunnel
spec:
  replicas: 1
  selector:
    deploymentconfig: wstunnel
  template:
    metadata:
      labels:
        deploymentconfig: wstunnel
    spec:
      containers:
      - name: wstunnel
        image: wstunnel
        command:
        - wstunnel
        args:
        - -s
        - 0.0.0.0:8080
        ports:
        - containerPort: 8080
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: false
      containerNames:
      - wstunnel
      from:
        kind: ImageStream
        name: wstunnel